### ISSUE TITLE
Couldn't find a Board on the selected port. Check that you have the correct port selected.  If it is correct, try pressing the board's reset button after initiating the upload.

### ISSUE THREAD

**Issue by nohackcc** [HexAirbot/HexNanoMWC_QUAD#5]
Arduino: 1.6.0 (Mac OS X), Board: "Arduino Leonardo"

Sketch uses 25,522 bytes (89%) of program storage space. Maximum is 28,672 bytes.
Global variables use 1,863 bytes (72%) of dynamic memory, leaving 697 bytes for local variables. Maximum is 2,560 bytes.
processing.app.debug.RunnerException: Couldn't find a Board on the selected port. Check that you have the correct port selected.  If it is correct, try pressing the board's reset button after initiating the upload.
	at cc.arduino.packages.uploaders.SerialUploader.waitForUploadPort(Unknown Source)
	at cc.arduino.packages.uploaders.SerialUploader.uploadUsingPreferences(Unknown Source)
	at processing.app.debug.Compiler.upload(Unknown Source)
	at processing.app.Sketch.upload(Sketch.java:1218)
	at processing.app.Sketch.exportApplet(Sketch.java:1191)
	at processing.app.Sketch.exportApplet(Sketch.java:1163)
	at processing.app.Editor$DefaultExportHandler.run(Editor.java:2391)
	at java.lang.Thread.run(Thread.java:695)
Couldn't find a Board on the selected port. Check that you have the correct port selected.  If it is correct, try pressing the board's reset button after initiating the upload.

  This report would have more information with
  "Show verbose output during compilation"
  enabled in File > Preferences.
----------------------------------------------------------------
The Evironment is: OS X Yousemite ,Arduino 1.6.0, 
the board :Arduino leonardo
the port:/dev/tty.usbmodem1411(Arduino leonardo)
the Programmer:USBtinyISP

**Comment by nserebry** [comment]
I'm seeing the same error message, running MAC with Arduino 1.6.0,

**Comment by rylivin** [comment]
I am also getting this message. I am using Mac OS X Yosemite, Arduino 1.6.12, MKR100 (new). Have either of you, nserebry  and nohackcc, figure this out?
